// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QnxbZlWtBN0rA4F_-ofMprqlcungNZs',
    appId: '1:440680002716:web:f6d9b16ca06070210ba959',
    messagingSenderId: '440680002716',
    projectId: 'fir-99003',
    authDomain: 'fir-99003.firebaseapp.com',
    databaseURL: 'https://fir-99003-default-rtdb.firebaseio.com/',
    storageBucket: 'fir-99003.firebasestorage.app',
    measurementId: 'G-EV9MGFMH26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgBfr5euH4DXljRjQd4lQFReUPfJpWkHc',
    appId: '1:440680002716:android:896538bcb54c18240ba959',
    messagingSenderId: '440680002716',
    projectId: 'fir-99003',
    storageBucket: 'fir-99003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfbAeTgC0L9EDPxgMKsjujxswvPBqXZU',
    appId: '1:440680002716:ios:b5b4ae689fc8c0580ba959',
    messagingSenderId: '440680002716',
    projectId: 'fir-99003',
    storageBucket: 'fir-99003.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfbAeTgC0L9EDPxgMKsjujxswvPBqXZU',
    appId: '1:440680002716:ios:b5b4ae689fc8c0580ba959',
    messagingSenderId: '440680002716',
    projectId: 'fir-99003',
    storageBucket: 'fir-99003.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5QnxbZlWtBN0rA4F_-ofMprqlcungNZs',
    appId: '1:440680002716:web:39668967e5c9e1f50ba959',
    messagingSenderId: '440680002716',
    projectId: 'fir-99003',
    authDomain: 'fir-99003.firebaseapp.com',
    storageBucket: 'fir-99003.firebasestorage.app',
    measurementId: 'G-1388L85X7T',
  );

}
